### ISSUE TITLE
`BRANCH_NAME` build metadata is undocumented

### ISSUE THREAD

**Issue by thii** [buildbuddy-io/buildbuddy#1030]
It's supported but is not mentioned in the doc at https://docs.buildbuddy.io/docs/guide-metadata/.
https://github.com/buildbuddy-io/buildbuddy/blob/bab9c19635c2d53c4e158c51a4e566a6691d34be/server/build_event_protocol/accumulator/accumulator.go#L29

**Comment by siggisim** [comment]
Hey @thii - thanks for reporting! 

@tempoz could you take a look at this? Those docs are here: https://github.com/buildbuddy-io/buildbuddy/blob/master/docs/guide-metadata.md

**Comment by siggisim** [comment]
This documentation should be live now. Thanks again for reporting @thii!
