### ISSUE TITLE
BuildBuddy nodejs support

### ISSUE THREAD

**Issue by herman-rogers** [buildbuddy-io/buildbuddy#129]
More of a question than an issue but does build buddy support nodejs rules/toolchain? We're mostly utilizing a angular monorepo with bazel so curious about this.

**Comment by siggisim** [comment]
Hey @herman-rogers - nodejs rules should work just fine, but you'll likely need to do some toolchain setup.

I recommend starting with adding `rbe_autoconfig` to your WORKSPACE file:
https://releases.bazel.build/bazel-toolchains.html

And then adding these flags to your .bazelrc:
https://github.com/bazelbuild/bazel-toolchains/blob/master/bazelrc/bazel-2.0.0.bazelrc#L30

You can also try our basic BuildBuddy toolchain - but it's not as fully featured:
https://www.buildbuddy.io/docs/rbe-setup

Feel free to ping on Slack http://slack.buildbuddy.io/ or email me at siggi@buildbuddy.io and I'm happy to help you with toolchain setup.

Feel free to re-open this issue if there are any concrete errors you're seeing!
