### ISSUE TITLE
UX: Make it easy to copy a build target presented in the buildbuddy UI

### ISSUE THREAD

**Issue by mrmeku** [buildbuddy-io/buildbuddy#1380]
The most common flow I have when using buildbuddy for CI is to identify tests which failed, click into to see the details of a particular target, and eventually manually copy and paste the target so that I can test it locally while I fix the errors

This flow could be improved in a number of ways
1) Buildbuddy could supply me with a copy pastable command to run all failed tests locally
2) When I click into a particular target, there could be a button to click which would copy the target name to my clipboard

I would be a very happy camper if one or both of these UX tweaks are implemented :)

**Comment by siggisim** [comment]
Great ideas @mrmeku - we should definitely implement these!

**Comment by siggisim** [comment]
Hey @mrmeku - I addressed this in https://github.com/buildbuddy-io/buildbuddy/pull/1510 which adds quick copy buttons on both individual target pages and on any target lists (like failing tests).

That way if you want to re-run failing tests you can just do `bazel test <paste>`.

This should go live in this week's release (typically on Wednesdays). Let me know if this covers your use-case, if not - feel free to open another issue!

Thanks again for opening this issue, love these little usability improvements!
