### ISSUE TITLE
Allow expanding/hiding groups in the timing tab 

### ISSUE THREAD

**Issue by Qinusty** [buildbuddy-io/buildbuddy#14]
On larger builds the timing tab can get quite fully of irrelevant information, it would be nice to maybe show the top 4/5 entries per field and allow them to be expanded. 

This would be especially useful for the `grpc-command-<N>` groups which end up full of information which isn't necessarily relevant to most users.

![image](https://user-images.githubusercontent.com/7274845/80957535-3d1f7180-8dfb-11ea-8556-a94bca7bb8f9.png)

Also the option of merging all groups and just having the sorting would be incredibly useful for keeping an eye on larger actions without having to scan through each of the skyframe evaluators.

**Comment by siggisim** [comment]
Hey Josh - I partially addressed this in (hasn't made it to the Docker image yet):
https://github.com/buildbuddy-io/buildbuddy/commit/90436e538dd946cf02a67604340c8daa49dd254c

I'll need to mess around with the page sizes a bit to see what makes sense (might add a toggle there as well).

Great suggestion on the group merging, will leave this open until all points have been addressed.

**Comment by siggisim** [comment]
Hey @Qinusty 

Added grouping options and page size controls in commit https://github.com/buildbuddy-io/buildbuddy/commit/5b5a2379a04ce3d8529e6aac0d9252ea9ee85b5c

This allows you to select whether you want to group by thread or merge all groups. It also allows you to select how many events you want to see per thread.

That should address all of the concerns raised in this issue - let me know if you have others!

Here's a screenshot:
![image](https://user-images.githubusercontent.com/1704556/82072961-5c38c180-968d-11ea-84c7-af50289b95fe.png)
