### ISSUE TITLE
The buildbuddy repo is incompatible with OSS tooling

### ISSUE THREAD

**Issue by achew22** [buildbuddy-io/buildbuddy#16]
The BuildBuddy repo uses the Google convention of having a `go_library` named for each package you would like declared. Unfortunately this is incompatible with the opensource golang ecosystem which makes importing it to a standard golang tree impossible.

Would you be open to a PR that moves to a more standard OSS golang import path?

**Comment by siggisim** [comment]
We're just a couple of ex-Googlers who went with what we're used to 😂 

I think we'd be open to this at some point in the future - but right now we're moving quickly and think the migration would slow us down a bit more than we'd like.

The [go_default_library](https://github.com/bazelbuild/bazel-gazelle/issues/5) naming is probably our biggest annoyance with the OSS standard at the moment.

Where exactly do you see the breakage? With gazelle, or some other tool? I wonder if there is some workaround we can implement in the meantime.

**Comment by achew22** [comment]
> We're just a couple of ex-Googlers who went with what we're used to joy

Oh yeah, I know that feeling :wink: 

> Where exactly do you see the breakage? With gazelle, or some other tool? I wonder if there is some workaround we can implement in the meantime.

For starters, none of the [godocs work](https://pkg.go.dev/github.com/buildbuddy-io/buildbuddy?tab=doc) which makes it much harder as an outsider to delve into the project. In addition I get a lot of complaining from Gazelle when I run it.

It sounds to me like the big blocker is finding dev resources to do this, so I threw some 20% time with some bash and a couple of for loops change to make you conformant with the expectations of the OSS world. I have prepared #17 to demonstrate how it could be done.
