### ISSUE TITLE
Double-escaping: `&` appears as `&amp;`

### ISSUE THREAD

**Issue by jschaf** [buildbuddy-io/buildbuddy#231]
I have the following logs for one of my builds:

```
&amp;pgconn.connectError
```

It should be:

```
&pgconn.connectError
```

From https://app.buildbuddy.io/invocation/bf57ab30-a3a2-442f-bbe9-71e53df6b907?target=//base/db/pgtest:pgtest_test

**Comment by siggisim** [comment]
Hey @jschaf - thanks or reporting! 

It looks like this value comes from the test.xml file associated with that test (you can download that file at the bottom) of that page.

That test.xml file contains html entity escaped characters like `&amp;`

At the moment, we render those failure messages from the test.xml as plain text and do not render any html or html entities. Doing so would leave the BuildBuddy application open to XSS attacks.

Looking through the rules_go code, it looks like this is the library that converts go's test2json files into test.xml files that bazel can understand:
https://github.com/bazelbuild/rules_go/blob/642ff3d80c3454e8d9758c54ce6841cc089507be/go/tools/bzltestutil/xml.go#L78

If you look at the test data it takes a json file without entities:
https://github.com/bazelbuild/rules_go/blob/642ff3d80c3454e8d9758c54ce6841cc089507be/go/tools/bzltestutil/testdata/report.json

And converts it into xml with the escaped entities:
https://github.com/bazelbuild/rules_go/blob/642ff3d80c3454e8d9758c54ce6841cc089507be/go/tools/bzltestutil/testdata/report.xml

The XML Parser we use (the browser built-in [DomParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser)) doesn't seem to convert those entities back into unicode.

Not sure where the right place to fix this is - either in the rules_go json=>xml conversion, in our xml => document conversion, or at render time. Will have to do a little more digging.

**Comment by siggisim** [comment]
This should be fixed by https://github.com/buildbuddy-io/buildbuddy/pull/1365 which will go out in the next release!
