### ISSUE TITLE
No registered executors in pool "" with os "darwin" with arch "amd64"

### ISSUE THREAD

**Issue by bedbad** [buildbuddy-io/buildbuddy#2393]
Hello, BuildBuddy!
When getting started on BuildBuddy with Apple Silicon the very first build faced with the following error:

Building md4c failed: (Exit 34): UNAVAILABLE: Error scheduling execution task "/uploads/7288e302-fd27-495c-939f-ec94b5f27ffe/blobs/251686baefe82c2e0ab2b7f1f1617925cd1f955bbe4fa25f7f7d5f9f3f4dddee/189": rpc error: code = Unavailable desc = No registered executors in pool "" with os "darwin" with arch "amd64".
java.io.IOException: io.grpc.StatusRuntimeException: UNAVAILABLE: Error scheduling execution task "/uploads/7288e302-fd27-495c-939f-ec94b5f27ffe/blobs/251686baefe82c2e0ab2b7f1f1617925cd1f955bbe4fa25f7f7d5f9f3f4dddee/189": rpc error: code = Unavailable desc = No registered executors in pool "" with os "darwin" with arch "amd64".

Looks like you have no toolchain for that.

**Comment by siggisim** [comment]
Hey @bedbad - Only Linux executors are currently part of our free-tier cloud offering. 

If you'd like for us to set up a Mac/M1 pool for you for testing - george@buildbuddy.io can help you get set up if you send him an email!

**Comment by bedbad** [comment]
Is there a crosstool file to crosscompile from one to the other? Where can I se exact Linux executors provided?
There's isn't one for popular Linux arch too:
`in cc_toolchain_suite rule @buildbuddy_toolchain//:ubuntu1604_cc_toolchain_suite: cc_toolchain_suite '@buildbuddy_toolchain//:ubuntu1604_cc_toolchain_suite' does not contain a toolchain for cpu 'aarch64'`

**Comment by siggisim** [comment]
Cross-compiling is possible but requires some toolchain fiddling. Here's a command that works for the buildbuddy repo for example (using a Mac host and linux remote executors):
```
bazel test //... --remote_executor=remote.buildbuddy.io --host_cpu=k8 --cpu=k8 --crosstool_top=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain_suite --host_platform=@buildbuddy_toolchain//:platform_linux --extra_toolchains=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain --jobs=100
```

**Comment by bedbad** [comment]
The command you mentioned specifies platform_linux as a host and results in the same error. Is there a good resource on how to make working remote config for cross-compiling on Mac M1 with linux executor? I think it's quite common situation

**Comment by siggisim** [comment]
Make sure you specify the cpu and host_cpu flags - this command works on Mac hosts and linux remote executors for the buildbuddy repo. 

We do typically recommend that the executors and the bazel host match though.
