### ISSUE TITLE
BuildBuddy onprem to support cache compression?

### ISSUE THREAD

**Issue by wendyliga** [buildbuddy-io/buildbuddy#2980]
running bazel build with `--experimental_remote_cache_compression` on onprem docker `BuildBuddy v2.12.4 (41467653eedb096fe4c53341d8b4dcd36812283e) compiled with go1.18.1`

got this error 
```
ERROR: --experimental_remote_cache_compression requested but remote does not support compression
```

does this feature exist on the current version(am I missing a config?), or will it come in a future version?
_note: it works on cloud_

**Comment by siggisim** [comment]
Hey @wendyliga!

You'll need to enable this in your config for BuildBuddy to support compression:
```
cache:
  zstd_transcoding_enabled: true

```

**Comment by wendyliga** [comment]
i created a PR to add it on the doc
https://github.com/buildbuddy-io/buildbuddy/pull/2981

**Comment by siggisim** [comment]
Thank you!!!
