### ISSUE TITLE
Cloud I use external cas storage with buildbuddy, like bazel-remote

### ISSUE THREAD

**Issue by bytearth** [buildbuddy-io/buildbuddy#3105]
Some of the  Remote Execution Service  support external cas storage, such as buildfarm and buildbarn. 
I can't find the same usage in buildbuddy's docs.
Could you tell me whether buildbuddy support or will support this feature.

Thanks a lot !

**Comment by siggisim** [comment]
Hey @bytearth - we support using an external grpc cache with the BuildBuddy UI, but we don't currently support using an external cache for remote execution.

**Comment by bytearth** [comment]
> is there any doc about how to config？

**Comment by bytearth** [comment]
> 

Execuse me, maybe I cannot understand it. 
`--remote_cache=grpc(s)://MY_CACHE` is the param used for bazel,  how can `BUILDBUDDY_SERVER` fetch data from it. 

I have tried which your suggestion, and in the invocation webview,  some of the TAB works well, except for the TIMING TAB, like this: 
![image](https://user-images.githubusercontent.com/73961492/208817574-2d696bac-0c6b-45a4-9a3a-3e60b9edc7a6.png)

And If I point the remote_cache address to the buildbuddy server, the TIMING TAB also works well.  So in my opinion, I should use the BUILDBUDDY as my remote-cache,  or some features may not work.

**Comment by siggisim** [comment]
Some features will only using BuildBuddy are your remote cache (like cache stats), so we definitely recommend using it for both.

It should be able to fetch the timing profile from your other cache though - are you sure that the BuildBuddy server is able to make a network request to the other server?
