### ISSUE TITLE
Use GitHub App instead of user token

### ISSUE THREAD

**Issue by titanous** [buildbuddy-io/buildbuddy#3191]
[GitHub Apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps) are the improved way to authenticate as a service to GitHub, and allow the installation to get an auth token instead of relying on a single user's token.

This is important because using that token will bypass various restrictions, for example organizations that have a SSH CA set up and required, see this error when using Workflows:

```
Cloning target repo...
Cloning into '.'...
remote: This repository requires SSH certificate authentication. Contact the owner to receive a certificate.
fatal: unable to access 'https://github.com/REDACTED/REDACTED.git/': The requested URL returned error: 403
```

It also ensures that there is no single load-bearing user account for the Workflows setup.

**Comment by siggisim** [comment]
Github App support is now live. You can link a Github organization using the Github app flow here: https://app.buildbuddy.io/settings/org/github
