### ISSUE TITLE
Confusing log message on macOS during startup

### ISSUE THREAD

**Issue by guw** [buildbuddy-io/buildbuddy#3269]
Noticed the following during start of BuildBuddy locally:
```
2023/01/23 07:19:42.540 INF BuildBuddy v2.12.16 (ef1312bec990efa6d9d46da55361e96eae7c1467) compiled with go1.19.3
...
2023/01/23 07:19:43.788 INF Increasing open files limit 65535 => 10240
```

I've increased the macOS file limit on my system myself. Thus, this looks odd: `65535 => 10240`. Is BuildBuddy decreasing the open files limit?

**Comment by siggisim** [comment]
I've noticed this as well in the past. Sent https://github.com/buildbuddy-io/buildbuddy/pull/3273 to fix.

**Comment by siggisim** [comment]
This should now be fixed!
