### ISSUE TITLE
bytestream_url override

### ISSUE THREAD

**Issue by com6056** [buildbuddy-io/buildbuddy#3377]
I was wondering if it was possible to override the `bytestream_url` that buildbuddy uses in the UI to retrieve things like the profile, artifacts, and the timing info.

Right now, we have some clients that use a proxy service to connect to our bazel cache via a localhost URL. Buildbuddy accesses it via a different URL though via a Kubernetes service.

Is there a way to tell buildbuddy that even though the client provided a URL for accessing the cache, it should use a different URL?

Thanks!

**Comment by siggisim** [comment]
Hey @com6056 - you can use the [--remote_bytestream_uri_prefix](https://bazel.build/reference/command-line-reference#flag--remote_bytestream_uri_prefix)= bazel flag to override URL to point at your bazel cache rather than the localhost url!
