### ISSUE TITLE
Locally Hosted Buildbuddy 'enable cache' option is barely visible.

### ISSUE THREAD

**Issue by marleypowell** [buildbuddy-io/buildbuddy#34]
The checkbox for 'enable cache' is barely visible unless selected.

This was found when running the build buddy OnPrem docker container.

![image](https://user-images.githubusercontent.com/55280588/90034431-86b01000-dcb8-11ea-8905-39df2f21c7f3.png)

**Comment by marleypowell** [comment]
It seems to be fine on my laptop display so maybe it was just the monitor that I was using that made this hard to see.

**Comment by siggisim** [comment]
The contrast ratio there definitely isn't very easy on the eyes.

I've fixed this in https://github.com/buildbuddy-io/buildbuddy/commit/5c7609e40fc1860115f1f63c2eaf6520315fd238

Should go live in the next release.

Thanks for reporting @marleypowell !
