### ISSUE TITLE
Janitor fails to delete blobs because directory is not empty

### ISSUE THREAD

**Issue by JaredNeil** [buildbuddy-io/buildbuddy#3464]
```WRN Error deleting blob (03516230-c019-4f85-8283-1059f6512a4a): remove /buildbuddy/03516230-c019-4f85-8283-1059f6512a4a: directory not empty```

I think this has something to do with how `Chunkstore` and `DiskBlobStore` interact, but I think it comes down to 
`DiskBlobStore.DeleteBlob` calls `disk.DeleteFile`, which calls `os.Remove`, which always fails because the blob is actually a directory, and not empty.

**Comment by tylerwilliams** [comment]
Hi @JaredNeil, sorry for the delay on this, but the fix is now submitted and will go out in next week's release :)
