### ISSUE TITLE
Official Helm chart

### ISSUE THREAD

**Issue by nathanhleung** [buildbuddy-io/buildbuddy#35]
Thanks for writing BuildBuddy! In addition to a pure [Kubernetes deployment](https://github.com/buildbuddy-io/buildbuddy/blob/master/docs/on-prem.md#kubernetes), do you have any plans to create an official Helm chart, so variables like the port number or number of replicas can be programmatically set via a standardized variables API?

**Comment by siggisim** [comment]
Hey @nathanhleung - great suggestion. It's on our roadmap, but not super high priority at the moment.

If it's a blocker for you all to adopt, let me know and we can definitely bump the priority!

**Comment by nathanhleung** [comment]
It might be a blocker since we're using Terraform to manage our cluster so we can't use the yaml output directly. We might be able to use the Docker image and manually provision all the extra resources (s3 bucket, etc) ourselves but I haven't looked too deeply into that yet. Thanks for your response!

**Comment by siggisim** [comment]
Hey @nathanhleung - thanks for this awesome suggestion!

I spent the last couple of days putting together an official BuildBuddy helm repo: https://github.com/buildbuddy-io/buildbuddy-helm

We now have charts for:
 - [Open Source BuildBuddy](https://github.com/buildbuddy-io/buildbuddy-helm/tree/master/charts/buildbuddy)
 - [Enterprise BuildBuddy](https://github.com/buildbuddy-io/buildbuddy-helm/tree/master/charts/buildbuddy-enterprise)

They support all the bells and whistles from optionally deploying MySQL to nginx, and more.

Please let me know if you run into any issues trying them out, I'd be happy to help debug.

Thanks again, and keep the suggestions coming!
