### ISSUE TITLE
Allow to set prefix for S3 storage

### ISSUE THREAD

**Issue by tIGO** [buildbuddy-io/buildbuddy#3595]
We use the same s3 bucket for buildbuddy and [bazel-remote](https://github.com/buchgr/bazel-remote). The latter allows to specify prefix via config, the former doesn't. It makes it hard to navigate bucket since the root is polluted and also to specify different lifecycle policies for cache and buildbuddy reports.

Basically, we want this kind of structure:
```
cache/
   ac/
   cas.v/
buildbuddy/
   24971223-462c-4a5d-85e7-3c6f8c50f0a6/
   24989c17-ab53-4744-ace6-d76ddda9d720/
   ...
```

**Comment by sluongng** [comment]
Hey @tIGO, is it possible if you could test https://github.com/buildbuddy-io/buildbuddy/pull/3597 out?

**Comment by sluongng** [comment]
@tIGO FYI this feature would be in the next release that is coming out today.

**Comment by sluongng** [comment]
We also implemented prefix support for the Build Event Storage (blob storage) in #3620.

This should be included in our weekly release next week. 🙇

**Comment by tIGO** [comment]
It works, thanks
