### ISSUE TITLE
Feature Request : Link to line in logs

### ISSUE THREAD

**Issue by karanjamutahi** [buildbuddy-io/buildbuddy#3838]
I'd like to be able to get a link to a line in the logs of a bazel invocation. 
Bonus if we can get a link to mutliline selection

**Comment by siggisim** [comment]
Hey @karanjamutahi - that's a great idea! Will take a look at what it'd take to implement and keep you posted.

**Comment by siggisim** [comment]
Hey @karanjamutahi - added support for this (single line selection and linking) in https://github.com/buildbuddy-io/buildbuddy/pull/3843

This should go out in this week's release (typically on Wednesdays). Should be able to get multi-line working at some point in the future as well.

Thanks again for the great feature request!
