### ISSUE TITLE
/ping endpoint

### ISSUE THREAD

**Issue by evis** [buildbuddy-io/buildbuddy#4722]
**Is your feature request related to a problem? Please describe.**

I want to deploy buildbuddy instances under a load balancer. When load balancer gets via non-200 ok response from `/ping`, then it should stop loading this instance with requests.

**Describe the solution you'd like**

New `/ping` endpoint.

**Describe alternatives you've considered**

I've searched for such endpoint in buildbuddy, but haven't found any.

For now, we've made `/ping` endpoint that always returns 200, but it doesn't check if buildbuddy is really healthy.

**Additional context**

**Comment by sluongng** [comment]
Hey @evis, how are you deploying BuildBuddy today?

If you are using our helm chart, these liveness and readiness probes should be set automatically

https://github.com/buildbuddy-io/buildbuddy-helm/blob/cde7a7f8dcb12047c7ddb016400199aeee98c7ed/charts/buildbuddy/templates/deployment.yaml#L73-L89

**Comment by sluongng** [comment]
Just a reminder: the FOSS version of BuildBuddy does not handle HA very well. Our enterprise version might serve your use case much better. If you are interested in the enterprise version, please contact us via https://www.buildbuddy.io/request-quote/ 🙇

**Comment by tylerwilliams** [comment]
Hi @evis,

BuildBuddy supports health checking either via the /healthz HTTP endpoint or via gRPC endpoint:

HTTP Example:
```bash
$ curl http://localhost:8080/healthz?server-type=buildbuddy-server
OK
$
```

gRPC Example:
```bash
$ grpcurl -plaintext localhost:1985 grpc.health.v1.Health.Check
{
  "status": "SERVING"
}
$

Cheers,
