### ISSUE TITLE
Does the non-enterprise on-prem version not support remote build execution?

### ISSUE THREAD

**Issue by fausturs** [buildbuddy-io/buildbuddy#4785]
I deployed an on-prem instance locally, the free version.

With the setting like
```
build --bes_results_url=http://localhost:8080/invocation/
build --bes_backend=grpc://localhost:1985
build --remote_cache=grpc://localhost:1985
build --remote_download_toplevel # Helps remove network bottleneck if caching is enabled
build --remote_timeout=3600
build --remote_executor=grpc://localhost:1985
```

add I get a error, when try build, 
> ERROR: Remote execution is not supported by the remote server, or the current account is not authorized to use remote execution.

If I remove the line of set remote executor
```
build --remote_executor=grpc://localhost:1985
```

it works well with cache.

But from the information given on this page, you can see that the personal version should also support RBE.
<img width="1298" alt="image" src="https://github.com/buildbuddy-io/buildbuddy/assets/25004087/e2a8f09f-aff5-4cf1-a5d6-58fa106c0eb3">

Is there something wrong with some of my settings?

I just follow the doc to deploy my instance:
> docker run -p 1985:1985 -p 8080:8080 gcr.io/flame-public/buildbuddy-app-onprem:latest

**Comment by siggisim** [comment]
Hello! The free / personal version of BuildBuddy version of BuildBuddy Cloud supports remote build execution, but the FOSS / free version of BuildBuddy on-prem only supports caching and UI.

**Comment by fausturs** [comment]
But what is the significance of such a limitation?

As an open source project, anyone can compile from the source code and get all the features of the enterprise version, right?

**Comment by siggisim** [comment]
The contents of the `enterprise` directory require a BuildBuddy Enterprise Subscription, as explained in the LICENSE file: https://github.com/buildbuddy-io/buildbuddy/blob/master/LICENSE

This is similar to other "[open-core](https://en.wikipedia.org/wiki/Open-core_model)" projects, like:
- [Gitlab](https://gitlab.com/gitlab-org/gitlab/-/blob/master/LICENSE?ref_type=heads)
- [Posthog](https://github.com/PostHog/posthog/blob/master/LICENSE)
- [Infisical](https://github.com/Infisical/infisical/blob/main/LICENSE)

The alternative is that we keep our enterprise code closed source, but we'd rather have it available for customers to inspect / modify / contribute to / etc.
