### ISSUE TITLE
[CLI] TCP error using `bb wtf`

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/buildbuddy#4994]
**Describe the bug**
I'm trying to use `bb wtf` and seeing a tcp error I don't understand

```
❯ bazel wtf
connection error: desc = "transport: Error while dialing: dial tcp: lookup 1cccd19e-b560-4bfc-a987-ff3f6bcbbacc: no such host"
```

**To Reproduce**

1. Have my computer
2. Type `bazel wtf` using the bazelisk version of the CLI installation

**Expected behavior**

It works, or tells me how to fix it

**Screenshots**

![CleanShot 2023-10-10 at 21 29 34@2x](https://github.com/buildbuddy-io/buildbuddy/assets/75236/da208c4c-ac42-403b-8506-715affc56991)

**Desktop (please complete the following information):**

- OS: macOS 14.0

**Comment by siggisim** [comment]
Ah we haven't launched this in prod yet (it's only enabled in our dev environment currently). 

Probably shouldn't show up in the help menu (yet!)

I'll try to get this launched in prod ASAP and ping you / update this issue when it's live.

**Comment by siggisim** [comment]
This is launched now!
