### ISSUE TITLE
[CLI] bb CLI very slow/does not run if using env -i in Bazel wrapper

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/buildbuddy#4995]
**Describe the bug**

Using a minimal Bazel wrapper (`tools/bazel`), invoking `bazel`/`bb` is extremely slow (~30 seconds to minutes). It typically errors out with:

```bash
could not run Bazel: could not start Bazel: fork/exec /Users/ekerber/Developer/slack/slack-objc/tools/bazel: resource temporarily unavailable
```

**To Reproduce**

1. Install the latest bb CLI via Bazelisk
2. Use a minimal Bazel wrapper that wraps invocations in `env -i`

```bash
#!/bin/bash

SANITIZED_ENVS=(
  PATH=/usr/bin:/bin
  HOME="$HOME"
)

env -i \
  "${SANITIZED_ENVS[@]}" \
  "${BAZEL_REAL}" "$@"
```

If I comment out `env -i` and `"${SANITIZED_ENVS[@]}"`, the CLi behaves as expected.

**Expected behavior**

Typing `bazel` results in showing help for Bazel and `bb` in milliseconds.

**Comment by sluongng** [comment]
Adding `BAZELISK_SKIP_WRAPPER` into the sanitized envs seems to solve the issue on my end

```
SANITIZED_ENVS=(
  PATH=/usr/bin:/bin
  HOME="$HOME"
  BAZELISK_SKIP_WRAPPER="$BAZELISK_SKIP_WRAPPER"
)
```

See https://github.com/bazelbuild/bazelisk/?tab=readme-ov-file#ensuring-that-your-developers-use-bazelisk-rather-than-bazel for more info.

**Comment by brentleyjones** [comment]
Yeah, I forgot about that. Here is the rules_xcodeproj change for the same reason: https://github.com/MobileNativeFoundation/rules_xcodeproj/commit/3c6c14e375f80dfd134aafda5f5f5b15b4d94110

**Comment by erikkerber** [comment]
Late here (we had a maelstrom of team offsites) but this works great. Thanks @sluongng
