### ISSUE TITLE
Buildbuddy does not work on Firefox

### ISSUE THREAD

**Issue by purkhusid** [buildbuddy-io/buildbuddy#5]
I was testing Buildbuddy locally from the master branch and I can´t seem to get it to work on Firefox.

It seems like it's related to the recent gzip change. Buildbuddy works fine on Firefox if I checkout the commit before gzip was introduced.

**Comment by tylerwilliams** [comment]
Hey Daniel,

Thanks for filing this! I just took a look, it appears Firefox won't decompress the gzipped response unless both "Transfer-Encoding" and "Content-Encoding" headers are set.

Fixed in c4a4051bfc3c9242e3438002cbd675f864c88c45.
