### ISSUE TITLE
in executor v2.29.2, podman ps does not work

### ISSUE THREAD

**Issue by oswalpalash** [buildbuddy-io/buildbuddy#5246]
**Describe the bug**
In the newly released version of the executor container, `v2.29.2` the podman commands seem to not work. 
`ps auxf` shows podman processes running, but `podman ps` does not show the running containers. 

**To Reproduce**

1. Trigger a remote build with `v2.29.2` container, I used this genrule:
```
genrule(
    name = "temp",
    outs = ["temp.txt"],
    cmd = """
    sleep 100000
    """,
    exec_properties = {
        # "workload-isolation-type": "firecracker",
    },
)
```
2. Exec into the RBE parent executor container, and do `podman ps` and it shows no containers. 

**Expected behavior**
`podman` cli to work.

**Screenshots**
<img width="934" alt="Screenshot 2023-11-09 at 7 10 45 AM" src="https://github.com/buildbuddy-io/buildbuddy/assets/6431196/49f9088a-5814-4aeb-8cc9-9af3da21d848">
<img width="934" alt="Screenshot 2023-11-09 at 7 11 19 AM" src="https://github.com/buildbuddy-io/buildbuddy/assets/6431196/4cc994e2-3e78-4046-8fb1-a318793a3be2">

**Comment by sluongng** [comment]
I wonder if this is caused by the container started with a different uid ($user) than the current uid of your shell.

Does "podman ps --all" show anything?

**Comment by oswalpalash** [comment]
@sluongng that doesn't list the procs either.
<img width="934" alt="Screenshot 2023-11-09 at 8 52 48 AM" src="https://github.com/buildbuddy-io/buildbuddy/assets/6431196/6b56158e-bc8b-417d-94fa-9846d6a55f41">

**Comment by sluongng** [comment]
It seems like `podman --transient-store ps` should work.

The flag allows us to start the container much faster, but the container information is stored in a different place that is incompatible with normal operation.
