### ISSUE TITLE
[CLI] Queries break if for some common attributes

### ISSUE THREAD

**Issue by erikkerber** [buildbuddy-io/buildbuddy#5248]
**Describe the bug**

In our `.bazelrc` we had JDK 11 specified under `common`:

```
common --java_runtime_version=remotejdk_11
common --tool_java_runtime_version=remotejdk_11
common --repo_env=JAVA_HOME=../bazel_tools/jdk
```

When installing the CLI via `.bazelversion`, queries then broke with an invalid option applied:

```
ERROR: --java_runtime_version=remotejdk_11 :: Unrecognized option: --java_runtime_version=remotejdk_11
```

Changing those to `build` resolves, but it feels like a bug that the wrapper isn't a pure passthrough in this instance

**To Reproduce**
(Above)

**Expected behavior**

The wrapper is completely transparent to regular Bazel operations

**Comment by bduffany** [comment]
@erikkerber the fix for this is now released in CLI version 5.0.25 !
