### ISSUE TITLE
Build Invocation Data not Shareable Across Docker containers even when stored in S3

### ISSUE THREAD

**Issue by nickden3** [buildbuddy-io/buildbuddy#5838]
**Describe the bug**
Using the config setting: `storage.aws_s3:` build data should be shareable between buildbuddy containers when looking at the same invocation id.  

**To Reproduce**
Start a buildbuddy container with storage.aws_s3 setting configured. Run a bazel build and note the inovcation ID. Verify the data lands in S3 for that ID.  Restart the buildbuddy container and go to http://localhost:8080/invocation/<invocationID> of the ID you just verified in S3 and buildbuddy returns a 404.

**Expected behavior**
I would expect any buildbuddy container that is configured to use S3 as data storage to be able to see invocation data of a build, given it exists in S3.

**Screenshots**
![Screenshot 2024-02-06 at 4 03 04 PM](https://github.com/buildbuddy-io/buildbuddy/assets/32907934/3075ed0d-2dca-402a-9b9f-9eeca5cb36a0)

**Desktop (please complete the following information):**

- OS: macOs 14.3
- Browser Chrome

**Comment by siggisim** [comment]
Hey @nickden3 - are you configuring a MySQL database? 
https://www.buildbuddy.io/docs/config-database

Invocation metadata is stored in the database, so that'd have to be shared in order to work across BuildBuddy servers.

**Comment by nickden3** [comment]
I am currently testing locally and believe I configured the sqllite db correctly, is there a way to confirm?

**Comment by siggisim** [comment]
Our SQLite implementation is only intended to support a single BuildBuddy instance. If you're trying to support multiple BuildBuddy instances, you'd need to use MySQL or PostegreSQL.

**Comment by nickden3** [comment]
understood, will give that a shot.  Thanks @siggisim.  Sounds like this issue can be closed.
