### ISSUE TITLE
Incorrect name and organization when logging in for the first time

### ISSUE THREAD

**Issue by fzakaria** [buildbuddy-io/buildbuddy#6075]
**Describe the bug**
Weird username and organization name when signing up.

**To Reproduce**
Login via SSO for the first time as Google or GitHub

**Expected behavior**
First user signup to work nicely.

**Screenshots**
Via Google SSO:
(I have nothing to do with HDL on GitHub)
![image](https://github.com/buildbuddy-io/buildbuddy/assets/605070/79a8eace-1d4a-4bb4-aa43-87dd2d9cd28c)

Via GitHub SSO:
![image](https://github.com/buildbuddy-io/buildbuddy/assets/605070/e985dd5c-fbef-4688-a0cb-4bf02c684329)
![image](https://github.com/buildbuddy-io/buildbuddy/assets/605070/7b9812f0-fe1e-4c59-94ab-aa5aa8a6c660)

**Desktop (please complete the following information):**

- OS: Chromebook
- Browser chrome

**Comment by fzakaria** [comment]
Yea i seemed to have picked up an organization somehow on first time login
![image](https://github.com/buildbuddy-io/buildbuddy/assets/605070/3e3a947c-3f15-411e-b173-9dc501f45733)

**Comment by siggisim** [comment]
Hey Farid, this is because some users from your email domain previously created an organization and checked the box

```
Automatically add anyone with an @XXX.com email address to this organization
```

**Comment by fzakaria** [comment]
@siggisim i uploaded the same photo many times oops -- 
![image](https://github.com/buildbuddy-io/buildbuddy/assets/605070/68819c0d-3d8b-4598-89a2-6ac6579dced3)

**Comment by fzakaria** [comment]
(updated description)

Is there a way to know who clicked that setting?

**Comment by siggisim** [comment]
Replied privately
