### ISSUE TITLE
Reclient/chromium build support?

### ISSUE THREAD

**Issue by Niek** [buildbuddy-io/buildbuddy#6134]
See: 
* https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#use-reclient
* https://github.com/bazelbuild/remote-apis#servers

BuildBuddy is mentioned here as a supported backend for building chromium using reclient. Is there any info if/how that works?

**Comment by siggisim** [comment]
Hey @Niek!

Our focus is on Bazel, but we do implement the REAPI so we do in theory support other clients that use the REAPI.

We don't offer any official docs / support on the subject because our focus is primarily on Bazel, but you're welcome to try to get it working!

**Comment by pl4nty** [comment]
I have reclient working with the new credential helper feature, but Brave still wouldn't build in the end. I've given up for now.

https://garden.tplant.com.au/Cloud/Building-Chromium

**Comment by pl4nty** [comment]
Thanks! I found how to use `env_var_allowlist` to overwrite the PATH, but couldn't quite figure out where rewrapper's `inputs` were on the BuildBuddy filesystem. maybe Brave has some EngFlow-specific workarounds or something. I'll definitely try BuildBuddy next time I'm building Chromium/Electron though

**Comment by sluongng** [comment]
I think reclient should be vendor-agnostic. There could be "missing" client-side features.

If you want to give it a try with BuildBuddy, feel free to join our Community Slack https://www.buildbuddy.io/contact/ and ask questions there. We have seen folks trying to use BuildBuddy with non-Bazel build tools, though it's hard to tell how much success they had without an event/telemetry system built into the client.
