### ISSUE TITLE
BuildBuddy GitHub app: Container has a version of `ar` without `--output=` flag

### ISSUE THREAD

**Issue by ivucica** [buildbuddy-io/buildbuddy#6228]
To unpack a `.deb` package and access header and library files inside, I have some custom rules that use `ar` to unpack the `.deb`, then `tar xfz` to unpack the contents of the archive.

Unfortunately, `ar` in the default container seems to be either too old or nonstandard: the version in GNU binutils that I have locally on multiple machines (and which seems to work fine unpacking files to provide them into RBE) seems to work perfectly fine.

Should `ar` / `binutils` be upgraded?

**Comment by siggisim** [comment]
Hey @ivucica! Does specifying the `container_image: ubuntu-20.04` option in your `buildbuddy.yaml` help?
Ex: https://github.com/buildbuddy-io/buildbuddy/blob/master/buildbuddy.yaml#L46

**Comment by ivucica** [comment]
Indeed, that works as well! I'll keep the approach of setting the CWD instead, since it has its own elegance, but yes, 20.04 has the newer `ar`. Sorry for the noise!
