### ISSUE TITLE
Feature Request: Show execution log in artifacts tab

### ISSUE THREAD

**Issue by brentleyjones** [buildbuddy-io/buildbuddy#6446]
**Is your feature request related to a problem? Please describe.**

When using the new `--experimental_execution_log_compact_file` flag (and currently `--remote_build_event_upload=all`) a compact execution log is uploaded to the remote cache. It is referenced in the `BuildToolLogs` event under the `"execution.log"` `name`. Currently this file doesn't show up in the Artifacts tab (or anywhere else).

**Describe the solution you'd like**

A link somewhere to easily download this file.

**Comment by sluongng** [comment]
We started to support compact execution log in our CLI with `bb print --compact_execution_log=log.binpb.zstd [--sort=true]`.

I think we could consider providing a dedicated UI for it once it hits a stable status. Right now it's still marked as unstable on the Bazel side with a few bugs reported.

In the meantime, I think we could render `bytestream://` URL in the Raw event tab as clickable. That way users could simply still these files themselves 🤔 

WDYT @siggisim ?

**Comment by brentleyjones** [comment]
> In the meantime, I think we could render bytestream:// URL in the Raw event tab as clickable. That way users could simply still these files themselves

I would like this as well, since what I did was manually take a URL from the artifacts page and replaced the digest with the one I cared about from the raw event.
