### ISSUE TITLE
[CLI]: bb plugin hardlink does not work in devcontainer's volume

### ISSUE THREAD

**Issue by qzmfranklin** [buildbuddy-io/buildbuddy#6567]
Config:

```bash
❯ cat /etc/os-release                                         
PRETTY_NAME="Ubuntu Noble Numbat (development branch)"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

```bash
❯ bb version                         
bb 5.0.61
```

Minimal Repro:

1. Create a symlink like this:
```bash
❯ ll ~/.cache/buildbuddy/ 
total 4.0K
lrwxrwxrwx 1 quzhongming quzhongming   38 May 14 05:06 plugins -> /.cache/quzhongming/buildbuddy/plugins
```

which points to
```bash
❯ ll /.cache/quzhongming/buildbuddy/plugins                    
total 4.0K
drwxr-xr-x 3 quzhongming quzhongming 4.0K May 14 05:07 github.com
```

Note that `/.cache` is a mounted container volume.

2. Run bb.

It will succeed.

2. In VSCode devcontainer, Rebuild Container
![image](https://github.com/buildbuddy-io/buildbuddy/assets/5695733/f631c3e0-c8f5-4348-a7f2-9275ffce0b3b)

4. Run bb.
For example:
```bash
❯ bb version                         
bb 5.0.61
Downloading "https://github.com/bduffany/go-highlight"
bazel setup: failed to add cloned repo to plugins dir: rename /tmp/buildbuddy-git-clone-3129895151 /home/quzhongming/.cache/buildbuddy/plugins/github.com/bduffany/go-highlight/latest: invalid cross-device link
```

This is where the problem occurs.

My research so far:

I Googled a bit and found that ` invalid cross-device link` indicates that a hardlink targets a difference device from its source.

Maybe: Change bb's logic so that it uses a symlink rather than a hardlink?

Why I need mounted volume for bb?

In China, downloading the bb plugins from github.com is slow and unreliable. Restarting my devcontainer means I'll have to retry. It's a pain in the AXX.

Thanks folks.

**Comment by bduffany** [comment]
@qzmfranklin this should be fixed now - thanks for the bug report and please let us know if you have any other feedback :)
