### ISSUE TITLE
[CLI] linux/arm64 support

### ISSUE THREAD

**Issue by arjantop-cai** [buildbuddy-io/buildbuddy#6813]
**Is your feature request related to a problem? Please describe.**
The current supported platforms work in most cases but do not work when:
* Running linux on MacOS arm via Parallels only supports running linux/arm64
* Running CLI on arm EC2 instances

**Describe the solution you'd like**
Release CLI for linux/arm64

**Comment by bduffany** [comment]
We should be able to add this pretty easily now that GitHub has arm64 runners. Will let you know when it's done!

**Comment by bduffany** [comment]
CLI version 5.0.75 now has an arm64 build available, and once https://github.com/buildbuddy-io/buildbuddy/pull/6814 is merged, future releases should have arm64 builds as well

**Comment by arjantop-cai** [comment]
@bduffany Thanks but bazelisk tries to download https://github.com/buildbuddy-io/bazel/releases/download/5.0.75/bazel-5.0.75-linux-arm64 with `arm64` arch and not `aarch64`

**Comment by sluongng** [comment]
@arjantop-cai yes `arm64` is the correct name according to Bazel release assets naming convention https://github.com/bazelbuild/bazel/releases

@bduffany it seems like CLI 5.0.76 is missing an arm64 build 🤔

**Comment by bduffany** [comment]
@sluongng the auto-release didn't kick in after I merged the GitHub workflow YAML, and I think another PR went in before I merged the YAML change, triggering the 5.0.76 build without arm64 support. Once https://github.com/buildbuddy-io/buildbuddy/pull/6832/files is merged, I'll manually kick off a release and we should have proper arm64 builds going forward :+1:

**Comment by bduffany** [comment]
Fixed in 5.0.77
