### ISSUE TITLE
Getting started doc for on prem misses vital information

### ISSUE THREAD

**Issue by konste** [buildbuddy-io/buildbuddy#7]
SETUP.md document basically lists only one command to run buildbuddy on prem: `bazel run -c opt server:buildbuddy` While this works a few vital pieces of information are missing and very much needed:
1. How to configure non-default ports for gRPC and HTTP?
2. How to stop buildbuddy in order to restart it with the different parameters?
3. In case it requires non-trivial amount of disk space to store build data - how to specify the folder where to keep it?
4. How to specify data retention period?
5. What other options are available?

**Comment by siggisim** [comment]
Hey @konste - thanks for bearing with us. Will be updating these docs ASAP.

To answer your question on restarting the server:
- If you're running it locally with bazel run, you should just be able to kill it and re-run it
- If you're running locally, but the process is in the background - you can [kill the process running on port 1985](https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux) with something like `kill -9 $(sudo lsof -t -i:1985)`
- If you're running on Kubernetes, you can just re-run the apply command.

If you're just looking to pass in a different config file, you can run with the flag:
`--config_file=enterprise/config/buildbuddy.prod.yaml`

I hear you though, the config is currently undocumented and we will fix that!

**Comment by tylerwilliams** [comment]
Hi @konste, small update here, we've documented all of the config file options and critical flags here: https://github.com/buildbuddy-io/buildbuddy/blob/master/CONFIG.md

If you're interested in running BuildBuddy on a different port, check out the bottom of that doc. Thanks for the nudge on this!

**Comment by tylerwilliams** [comment]
Going to close this for now -- feel free to file a new issue if you're still stuck.
