### ISSUE TITLE
redis_target section in (distributed) cache setting misleading

### ISSUE THREAD

**Issue by SjuulJanssen** [buildbuddy-io/buildbuddy#7350]
In discussions with Son last week he mentioned the built-in distributed cache should be used over the Redis cache. He also mentioned that Redis cache should be considered legacy. 

I think this config section is a little bit misleading: https://github.com/buildbuddy-io/buildbuddy/blob/1e41915c613916c2f9df4197559b192e35996f72/enterprise/server/backends/distributed/distributed.go#L44

>  redis target for improved Caching/RBE performance

**Comment by SjuulJanssen** [comment]
Also: Sry, the wording "misleading" might be a bit strong.

**Comment by siggisim** [comment]
Agreed, that comment looks like a copy / paste from another redis flag: https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/server/backends/redis_client/redis_client.go#L23

The originally linked (optiona) redis target is used for discovering app replicas in a distributed cluster setup.

**Comment by siggisim** [comment]
Sent https://github.com/buildbuddy-io/buildbuddy/pull/7351 to fix

**Comment by SjuulJanssen** [comment]
<3
