### ISSUE TITLE
Contribution model doc

### ISSUE THREAD

**Issue by JonathanPerry651** [buildbuddy-io/buildbuddy#7616]
could you please add a doc describing your contribution model? The current link doesn’t say anything about CLA or copyright assignment etc. 

Thank you!

**Comment by siggisim** [comment]
Hey @JonathanPerry651 - contributions to BuildBuddy are governed by GitHub's terms of service: https://github.com/github/site-policy/blob/1263bf0164cfe60d0900e70ba9126855c7c23c6c/Policies/github-terms-of-service.md#6-contributions-under-repository-license

> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms. If you have a separate agreement to license your contributions under different terms, such as a contributor license agreement, that agreement will supersede.
> 
> Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.
