### ISSUE TITLE
[RB/CLI] `bb remote` does not work in a Git worktree

### ISSUE THREAD

**Issue by goniz** [buildbuddy-io/buildbuddy#7896]
**Describe the bug**
Trying to run `bb remote` in a Git worktree directory, it fails with:
`remote config: determine remote: the git repository must have a remote configured to use remote Bazel`

**To Reproduce**

1. Clone a git repo
2. Create a new worktree using `git worktree add /path/to/worktree-dir $ref`
3. `cd /path/to/worktree-dir`
4. `bb remote run $label`

**Additional context**
A worktree path does not have a `.git` directory , which probably is the cause for the failure(?)

**Comment by maggie-lou** [comment]
Sounds good. I've been meaning to refactor out go-git anyway. There have been a series of unhandled edge cases
