### ISSUE TITLE
Timeout when building java targets w/ BB RBE + java toolchain (bazel_tools)

### ISSUE THREAD

**Issue by kunal-rp** [buildbuddy-io/buildbuddy#848]
I am integrating remote cache + execution on local bazel repo and am running into for building any java targets. Currently setup to use bazel_tool jdk11 toolchains and base image. I am able to build everything locally but not through rbe 

Bazel version : 4.1.0

Build stalls when executing this bazel_tools action : https://github.com/bazelbuild/bazel/blob/master/tools/jdk/DumpPlatformClassPath.java 

Example failed build : https://app.buildbuddy.io/invocation/94246fde-8d83-4f46-bfee-2ea575b614cb

.bazelrc
```
build:remote --javabase=@bazel_tools//tools/jdk:remote_jdk11
build:remote --host_javabase=@bazel_tools//tools/jdk:remote_jdk11
build:remote --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
build:remote --java_toolchain=@bazel_tools//tools/jdk:toolchain_java11
```

WORKSPACE 
```
# java - jdk 
http_archive(
    name = "rules_java",
    sha256 = "220b87d8cfabd22d1c6d8e3cdb4249abd4c93dcc152e0667db061fb1b957ee68",
    url = "https://github.com/bazelbuild/rules_java/releases/download/0.1.1/rules_java-0.1.1.tar.gz",
)

load("@rules_java//java:repositories.bzl", "rules_java_dependencies")
rules_java_dependencies()

...

#build buddy
http_archive(
    name = "io_buildbuddy_buildbuddy_toolchain",
    sha256 = "a2a5cccec251211e2221b1587af2ce43c36d32a42f5d881737db3b546a536510",
    strip_prefix = "buildbuddy-toolchain-829c8a574f706de5c96c54ca310f139f4acda7dd",
    urls = ["https://github.com/buildbuddy-io/buildbuddy-toolchain/archive/829c8a574f706de5c96c54ca310f139f4acda7dd.tar.gz"],
)

load("@io_buildbuddy_buildbuddy_toolchain//:deps.bzl", "buildbuddy_deps")

buildbuddy_deps()

load("@io_buildbuddy_buildbuddy_toolchain//:rules.bzl", "buildbuddy")

buildbuddy(name = "buildbuddy_toolchain")

```
java dep : https://github.com/bazelbuild/rules_java/blob/ca8f85f30491148dc86865e1e799d96410f31500/java/repositories.bzl#L505

**Comment by siggisim** [comment]
Hey @kunal-rp - it looks like you're trying a Mac (darwin) build. Unfortunately only Linux builds are currently supported with the free tier of BuildBuddy's Cloud service.

If you'd like us to provision some Mac executors for you, you can request a quote [here](https://www.buildbuddy.io/request-quote).

We're working on removing this limitation, but there are some technical blockers at the moment.

**Comment by kunal-rp** [comment]
For my understanding, is the issue the host platform( my macbook ) ? The end product of my builds are multiple docker images meaning I'll need to build for linux os & amd CPU

here are my platform settings ; 
```
build:remote --host_platform=@buildbuddy_toolchain//:platform
build:remote --platforms=@buildbuddy_toolchain//:platform
build:remote --extra_execution_platforms=@buildbuddy_toolchain//:platform
build:remote --crosstool_top=@buildbuddy_toolchain//:toolchain
build:remote --extra_toolchains=@buildbuddy_toolchain//:cc_toolchain
```

if it is an issue w/ the host platform, based on the build buddy toolchain implementation (https://github.com/buildbuddy-io/buildbuddy-toolchain/blob/master/rules.bzl#L31) it seems like the platform & cc toolchain are decided based system provided context (https://docs.bazel.build/versions/main/skylark/lib/repository_ctx.html#os) , meaning that changing the host platform ( --platforms ) would not fix the issue right ?

**Comment by siggisim** [comment]
The buildbuddy toolchain by default selects which toolchains to use based on your host platform.

It's possible to compile from a Mac host on Linux executors, but it's very build specific and there are a whole host of issues that can make this challenging.

If you'd like to try it out, here are a set of flags that work when compiling the bazel project on Linux executors from a Mac host:

```
bazel build src:bazel --remote_executor=remote.buildbuddy.io --host_cpu=k8 --cpu=k8 --crosstool_top=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain_suite --host_platform=@buildbuddy_toolchain//:platform_linux --extra_toolchains=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain --jobs=100 --bes_backend=remote.buildbuddy.io --bes_results_url=https://app.buildbuddy.io/invocation/ --remote_timeout=600 --javabase=@bazel_tools//tools/jdk:remote_jdk11 --host_javabase=@bazel_tools//tools/jdk:remote_jdk11 --nojava_header_compilation
```

**Comment by kunal-rp** [comment]
hmm still running into the same stall : https://app.buildbuddy.io/invocation/7f8335ff-b8c5-406e-b32c-39a6f40c4acf

realistically how far off are mac executors on the free tier ?

**Comment by siggisim** [comment]
Unfortunately it's not on our short term roadmap as there aren't any great options for running Mac VMs at the moment - we actually need to provision bare metal Macs as exectors. (There are solutions like MacStadium's Orka out there, but in our experience the performance just isn't there for RBE).
