### ISSUE TITLE
Tag / release missing for 0.0.4

### ISSUE THREAD

**Issue by jsharpe** [buildbuddy-io/buildbuddy#9]
It'd be useful if you could tag / release the code at the point that the docker container is built so we have a reference for which version of the code is in use

**Comment by tylerwilliams** [comment]
Hi @jsharpe, yup this is on our list! Should have an update for you soon here.

**Comment by tylerwilliams** [comment]
Alright, fixed by adding a release script. We'll use that when we generate a release going forward, and it updates the docker image as part of the release process. Cheers.
